import { Express } from "express";
import { Pool } from "mysql2/promise";

import { authRoutes } from "./authRoutes";
import { dashboardRoutes } from "./dashboardRoutes";
import { projectRoutes } from "./projectRoutes";
import { cardRoutes } from "./cardRoutes";
import { fileRoutes } from "./fileRoutes";
import { chartRoutes } from "./chartRoutes";
import { auditLogsRoutes } from "./auditLogs";
import { scheduleRoutes } from "./scheduleRoutes";
import { notificationRoutes } from "./notificationRoutes";
import { notificationSettingsRoutes } from "./notificationSettingsRoutes";
import { templateRoutes } from "./templateRoutes";
import { adminUserRoutes } from "./adminUserRoutes";
import { systemRoutes } from "./systemRoutes";
import { collabRoutes } from "./collabRoutes";
import { dataQaRoutes } from "./dataQaRoutes";
import { searchRoutes } from "./searchRoutes";
import { exportRoutes } from "./exportRoutes";
import { exportPptxRoutes } from "./exportPptx";
import { ingestionSourceRoutes } from "./ingestionSourceRoutes";
import { agentIngestionRoutes } from "./agentIngestionRoutes";
import { impactRoutes } from "./impactRoutes";
import { dataQualityRoutes } from "./dataQualityRoutes";
import { operationsRoutes } from "./operationsRoutes";
import { alertRoutes } from "./alertRoutes";
import { partnerScorecardRoutes } from "./partnerScorecardRoutes";
import { reportRoutes } from "./reportRoutes";

export const setRoutes = (app: Express, dbPool: Pool) => {
  app.use("/api/auth", authRoutes(dbPool));
  app.use("/api/dashboard", dashboardRoutes(dbPool));
  app.use("/api/projects", projectRoutes(dbPool));
  app.use("/api/cards", cardRoutes(dbPool));
  app.use("/api/files", fileRoutes(dbPool));
  app.use("/api/charts", chartRoutes(dbPool));
  app.use("/api/audit-logs", auditLogsRoutes());
  app.use("/api/schedules", scheduleRoutes(dbPool));
  app.use("/api/notifications", notificationRoutes(dbPool));
  app.use("/api/notification-settings", notificationSettingsRoutes(dbPool));
  app.use("/api/templates", templateRoutes(dbPool));
  app.use("/api/admin/users", adminUserRoutes(dbPool));
  app.use("/api/system", systemRoutes(dbPool));
  app.use("/api/reports", reportRoutes(dbPool));
  app.use("/api/collab-sessions", collabRoutes(dbPool));
  app.use("/api/data-qa", dataQaRoutes(dbPool));
  app.use("/api/search", searchRoutes(dbPool));
  app.use("/api/export", exportRoutes(dbPool));
  app.use("/api/export", exportPptxRoutes(dbPool));
  app.use("/api/sources", ingestionSourceRoutes(dbPool));
  app.use("/api/ingest", agentIngestionRoutes(dbPool));
  app.use("/api/impact", impactRoutes(dbPool));
  app.use("/api/data-quality", dataQualityRoutes(dbPool));
  app.use("/api/operations", operationsRoutes(dbPool));
  app.use("/api/alerts", alertRoutes(dbPool));
  app.use("/api/partner-scorecard", partnerScorecardRoutes(dbPool));
};
